<a href="https://colab.research.google.com/github/jatingupta74/python/blob/main/Prac_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# a. Two-dimensional array
arr1 = np.random.rand(7, 8)

mean_arr1 = np.mean(arr1, axis=1) # Mean
std_arr1 = np.std(arr1, axis=1) # Std Dev
var_arr1 = np.var(arr1, axis=1) # Variance

print("arr1:")
print(arr1)
print("Mean along second axis:", mean_arr1)
print("Standard Deviation along second axis:", std_arr1)
print("Variance along second axis:", var_arr1)




arr1:
[[0.35169463 0.04258505 0.2149385  0.19506181 0.23549081 0.73417715
  0.22298429 0.66784679]
 [0.85422569 0.84833689 0.08429102 0.76965671 0.32714313 0.62645689
  0.42425535 0.72646065]
 [0.91667876 0.36830988 0.92968622 0.45887681 0.03365306 0.51183899
  0.36144627 0.50322747]
 [0.18112213 0.3971462  0.4843329  0.33140489 0.83376609 0.61194147
  0.11230838 0.78522984]
 [0.00175166 0.47377848 0.26819588 0.72454015 0.66336137 0.8680273
  0.08596652 0.1509147 ]
 [0.50287054 0.2467568  0.190781   0.28289091 0.58611089 0.88055928
  0.58988151 0.18236558]
 [0.30294533 0.705913   0.72368771 0.39400161 0.56221471 0.20709662
  0.68218924 0.77131436]]
Mean along second axis: [0.33309738 0.58260329 0.51046468 0.46715649 0.40456701 0.43277707
 0.54367032]
Standard Deviation along second axis: [0.22702772 0.25996375 0.27686548 0.24695489 0.30324208 0.23236622
 0.20115704]
Variance along second axis: [0.05154159 0.06758115 0.07665449 0.06098672 0.09195576 0.05399406
 0.04046415]


In [10]:
# b. Create a 2-dimensional array of size m x n, print shape, type, and data type, and reshape

#Taking Input
m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

#Two-dimentional Array
arr2 = np.random.randint(0, 20, size=(m, n))

print("arr2:")
print(arr2)

#Shape
print("Shape:", arr2.shape)

#Type
print("Type:", type(arr2))

#Datatype
print("Data Type:", arr2.dtype)

#Reashaped
arr2_reshaped = arr2.reshape(n, m)
print("arr2 Reshaped:")
print(arr2_reshaped)


Enter the number of rows (m): 8
Enter the number of columns (n): 9
arr2:
[[11  5  0  0  8 19 13  5 17]
 [ 7 17  1  6 17  1  0 18 17]
 [ 6  4  9  7  1  8 11  0 10]
 [12 11  4 19 10  8 13  2  7]
 [ 3  2 10  7 17 18  9  1  6]
 [ 4  5 11 13 12  1  7  4 13]
 [ 9  5 10 14 13 14  6 11 15]
 [ 9 18  1 10  1 12  2  0  1]]
Shape: (8, 9)
Type: <class 'numpy.ndarray'>
Data Type: int64
arr2 Reshaped:
[[11  5  0  0  8 19 13  5]
 [17  7 17  1  6 17  1  0]
 [18 17  6  4  9  7  1  8]
 [11  0 10 12 11  4 19 10]
 [ 8 13  2  7  3  2 10  7]
 [17 18  9  1  6  4  5 11]
 [13 12  1  7  4 13  9  5]
 [10 14 13 14  6 11 15  9]
 [18  1 10  1 12  2  0  1]]


In [11]:
# c. Test whether elements of a given 1D array are zero, non-zero, and NaN. Record indices.
arr3 = np.array([1.0, 0.0, 3.0, np.nan, 5.0, 0.0])
zero_indices = np.where(arr3 == 0)[0]
nonzero_indices = np.where(arr3 != 0)[0]
nan_indices = np.where(np.isnan(arr3))[0]

print("arr3:", arr3)
print("Zero indices:", zero_indices)
print("Non-zero indices:", nonzero_indices)
print("NaN indices:", nan_indices)
print("\n")

arr3: [ 1.  0.  3. nan  5.  0.]
Zero indices: [1 5]
Non-zero indices: [0 2 3 4]
NaN indices: [3]




In [12]:
# d. Create three random arrays, perform operations, find covariance and correlation
Array1 = np.random.rand(6)
Array2 = np.random.rand(6)
Array3 = np.random.rand(6)

Array4 = Array3 - Array2
Array5 = 2 * Array1

covariance = np.cov(Array1, Array4)[0, 1]
correlation = np.corrcoef(Array1, Array5)[0, 1]

print("Array1:", Array1)
print("Array2:", Array2)
print("Array3:", Array3)
print("Array4 (Array3 - Array2):", Array4)
print("Array5 (2 * Array1):", Array5)
print("Covariance of Array1 and Array4:", covariance)
print("Correlation of Array1 and Array5:", correlation)


Array1: [0.60110262 0.601831   0.99576369 0.73306136 0.90229341 0.18951044]
Array2: [0.39835181 0.18116966 0.61340984 0.79521602 0.64851095 0.41684485]
Array3: [0.91618579 0.57184066 0.05932659 0.98635166 0.42969873 0.08524108]
Array4 (Array3 - Array2): [ 0.51783398  0.390671   -0.55408325  0.19113564 -0.21881221 -0.33160378]
Array5 (2 * Array1): [1.20220524 1.20366199 1.99152737 1.46612272 1.80458682 0.37902088]
Covariance of Array1 and Array4: -0.02444991694915765
Correlation of Array1 and Array5: 1.0


In [13]:
# e. Create two random arrays, find sum of first half and product of second half
Array6 = np.random.rand(10)
Array7 = np.random.rand(10)

sum_first_half = np.sum(Array6[:5]) + np.sum(Array7[:5])
product_second_half = np.prod(Array6[5:]) * np.prod(Array7[5:])

print("Array6:", Array6)
print("Array7:", Array7)
print("Sum of first half:", sum_first_half)
print("Product of second half:", product_second_half)




Array6: [0.18752204 0.44778563 0.46147789 0.28526134 0.0996272  0.22051482
 0.89568157 0.91009942 0.17666677 0.04319338]
Array7: [0.0675007  0.45987847 0.87308407 0.93931165 0.68519689 0.72305084
 0.45912157 0.67957977 0.00348359 0.52925079]
Sum of first half: 4.506645878034314
Product of second half: 5.705293952456433e-07


In [14]:
# f. Create an array with random values, determine the size of the memory occupied
Array8 = np.random.rand(4, 5)
memory_size = Array8.nbytes

print("Array8:")
print(Array8)
print("Memory occupied by Array8:", memory_size, "bytes")
print("\n")

Array8:
[[0.89965388 0.0437188  0.58996623 0.99183496 0.43982644]
 [0.75573461 0.11136796 0.06874838 0.8604198  0.51690712]
 [0.46481194 0.14144261 0.48589228 0.48316188 0.85874636]
 [0.77076354 0.94611116 0.97464347 0.31733081 0.23122835]]
Memory occupied by Array8: 160 bytes




In [15]:
# g. Create a 2-dimensional array of size m x n with integer elements in the range (10,100)
m_g = 4
n_g = 3
ARR_g = np.random.randint(10, 100, size=(m_g, n_g))
print("Original ARR_g:")
print(ARR_g)

# Swap two rows (e.g., swap row 1 and row 2)
ARR_g_swapped_rows = ARR_g.copy()
ARR_g_swapped_rows[1], ARR_g_swapped_rows[2] = ARR_g_swapped_rows[2].copy(), ARR_g_swapped_rows[1].copy()
print("ARR_g after swapping rows:")
print(ARR_g_swapped_rows)

# Reverse a specified column (e.g., reverse column 1)
ARR_g_reversed_column = ARR_g.copy()
ARR_g_reversed_column[:, 0] = np.flipud(ARR_g_reversed_column[:, 0])
print("ARR_g after reversing column:")
print(ARR_g_reversed_column)


Original ARR_g:
[[71 50 76]
 [45 80 66]
 [64 23 84]
 [48 33 56]]
ARR_g after swapping rows:
[[71 50 76]
 [64 23 84]
 [45 80 66]
 [48 33 56]]
ARR_g after reversing column:
[[48 50 76]
 [64 80 66]
 [45 23 84]
 [71 33 56]]
